In [2]:
import numpy as np


In [3]:
angle = np.arange(0,361,90)
angle

array([  0,  90, 180, 270, 360])

In [7]:
np.random.random((3,3))

array([[0.8084186 , 0.15863731, 0.14282955],
       [0.45397536, 0.0020747 , 0.0463126 ],
       [0.2035746 , 0.2630881 , 0.06483028]])

In [5]:
np.random.randint(0,10,(3,3))

array([[5, 1, 0],
       [2, 4, 6],
       [4, 0, 3]], dtype=int32)

In [10]:
a = ["pla","plapla","plaplapla"]
ana =np.random.choice(a,size=(3,3))
ana

array([['plapla', 'pla', 'plaplapla'],
       ['plaplapla', 'plaplapla', 'plapla'],
       ['plaplapla', 'pla', 'pla']], dtype='<U9')

In [16]:
mat1 = np.ones((3,4))
print(mat1)
print("="*20)
mat2 = np.zeros((3,4))
print(mat2)
print("="*20)
np.savez("np_file.npz",cat = mat1,dog = mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
"""open file task"""

In [21]:
m1 = np.array([[1,2,3],[0,0,0]])
m2 = np.array([[2,3,4],[4,0,5]])

new = np.stack((mat1,mat2))
new


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
v1 = np.array([1,2,3,0,0,0])
v2 = np.array([1,2,3,0,0,0])
v1==v2

array([ True,  True,  True,  True,  True,  True])

In [27]:
v = np.array([4,65,3,4,9,3])
np.all(v>2)

np.True_

In [30]:
v1 = np.array([5,1,2,0,0,0])
v2 = np.array([1,2,3,4,6,0])
np.isclose(v1,v2,atol = 1)

array([False,  True,  True, False, False,  True])

In [31]:
v1 = np.array([5,1,2,0,0,0])
v2 = np.array([1,2,3,4,6,0])
comd= v1 == 0 

v1[comd] = 2

v1

array([5, 1, 2, 2, 2, 2])